### ISSUE TITLE
Copyright notice

### ISSUE THREAD

**Issue by rubenv** [tnayuki/angular-gettext-rails#1]
Hi,

I'm flattered that you made a module to ship angular-gettext with rails. That's awesome.

Since you are embedding a copy of the angular-gettext source, would you be so kind to include the correct copyright notice, as the license requires? It's over here: https://github.com/rubenv/angular-gettext/blob/master/LICENSE

**Comment by toru-unity** [comment]
Thank you for pointing it out.
I added correct copyright notices, and also bumped to brand-new version of angular-gettext!

**Comment by tnayuki** [comment]
Thank you for pointing it out.
I added correct copyright notices, and also bumped to brand-new version of angular-gettext!

**Comment by rubenv** [comment]
Cool, thanks! 

And thanks again for this gem!
